export enum ResultCode {
    MESSAGE_CREATED,
    MESSAGE_DROPPED,
    MESSAGE_NOT_AVAILABLE,
    MESSAGE_DEQUEUED,
    MESSAGE_NOT_FOUND,
    MESSAGE_STATE_INVALID,
    MESSAGE_COMPLETED,
    MESSAGE_DEFERRED,
    MESSAGE_HEARTBEATED,
    CHANNEL_NOT_FOUND,
    CHANNEL_RELEASED,
}

export const INTEGER_MAX = 2_147_483_647
